name: NASA Project CI
on:
  push:
   branches: [ main ]
  pull_request:
   branches: [ main ]
jobs:
  build:
    env:
      CI: true  #build is running in a CI environment
      MONGO_URL: mongodb://localhost/nasa
    strategy:
      matrix:
        node-version: ['20.11.1']
        mongodb-version: ['7.0.8']
    runs-on: ubuntu-latest #ubuntu is OS on Linux
    steps: 
     - uses: actions/checkout@v4
     - name: Use Node.js version ${{matrix.node-version}}
       uses: actions/setup-node@v4
       with:
         node-version: ${{ matrix.node-version }}
     - name: Use MongoDB from GitHub Actions
       uses: supercharge/mongodb-github-action@1.6.0
     - run: npm install
     - run: npm run build --prefix nasa-front-end   
     - run: npm test